# Generated by Django 2.0.3 on 2018-03-17 23:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20180317_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapentry',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
