# Generated by Django 2.0.3 on 2018-03-19 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_mapentry_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapentry',
            name='position',
        ),
    ]
