# Generated by Django 2.0.3 on 2018-04-01 22:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_remove_mapentry_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapentry',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location(click on the marker to select your location on map)'),
        ),
        migrations.AlterField(
            model_name='mapentry',
            name='name',
            field=models.CharField(blank=True, help_text="Leave blank if it's yourself", max_length=256, null=True, verbose_name='Name of Company'),
        ),
    ]
