# Generated by Django 3.2 on 2021-07-11 18:12
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo_image",
                    models.ImageField(
                        null=True, upload_to="images/", verbose_name="Company logo"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=145, verbose_name="Company name"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Describe your companies"),
                ),
                (
                    "website_url",
                    models.URLField(
                        blank=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_url",
                                message="Website URL must include https:// or http://",
                                regex="[http]",
                            )
                        ],
                        verbose_name="Link to your website",
                    ),
                ),
                (
                    "relation_to_django",
                    models.TextField(verbose_name="Your relation to Django"),
                ),
                ("email", models.EmailField(max_length=100)),
                (
                    "main_contact",
                    models.CharField(
                        max_length=100, verbose_name="The main point of contact"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
