# Generated by Django 3.2 on 2021-05-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=145)),
                ('description', models.TextField()),
                ('eventUrl', models.CharField(max_length=100)),
                ('eventImage', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
