# Generated by Django 3.2.5 on 2021-07-11 12:13
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_title", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=145)),
                ("description", models.TextField()),
                ("event_url", models.CharField(max_length=100)),
                (
                    "event_image",
                    models.ImageField(null=True, upload_to="images/events/"),
                ),
            ],
        ),
    ]
