# Generated by Django 3.2.2 on 2021-05-13 14:38
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Jobpost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobTitle", models.CharField(max_length=60)),
                ("jobCompanyName", models.CharField(max_length=100)),
                ("jobDescription", models.TextField()),
                (
                    "jobType",
                    models.CharField(
                        choices=[
                            ("PartTime", "Part-time"),
                            ("FullTime", "Full-time"),
                            ("Freelancer", "Freelancer"),
                            ("Internship", "Internship"),
                            ("Other", "Other"),
                        ],
                        max_length=11,
                    ),
                ),
                ("jobLocation", models.CharField(max_length=100)),
                ("jobContactPerson", models.CharField(max_length=80)),
                ("jobApplyHere", models.CharField(max_length=150)),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
