# Generated by Django 3.2 on 2021-05-18 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='jobApplyHere',
            field=models.URLField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_url', message='Job link must include https:// or http://', regex='[http]')]),
        ),
    ]
