# Generated by Django 3.2 on 2021-05-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='houseNumber',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='company',
            name='mainContact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='phoneNumber',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='company',
            name='postalCode',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='company',
            name='streetName',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='company',
            name='websiteURL',
            field=models.CharField(max_length=100),
        ),
    ]
