# Generated by Django 3.2 on 2021-05-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='compamyAddress',
            new_name='companyAddress',
        ),
    ]
