# Generated by Django 3.2.2 on 2021-05-07 13:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_company_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="phoneNumber",
            field=models.CharField(max_length=15),
        ),
    ]
