# Generated by Django 3.2 on 2021-05-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20210506_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logoImage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
