# Generated by Django 3.2 on 2021-05-18 11:26
import django.core.validators
from django.db import migrations
from django.db import models

import company.models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_alter_company_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="phoneNumber",
            field=models.CharField(max_length=15, validators=[company.models.only_int]),
        ),
        migrations.AlterField(
            model_name="company",
            name="websiteURL",
            field=models.URLField(
                blank=True,
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_url",
                        message="Website URL must include https:// or http://",
                        regex="[http]",
                    )
                ],
            ),
        ),
    ]
